### ISSUE TITLE
Capture date text on the frame is incorrect if RAW file has been resaved/modified

### ISSUE THREAD

**Issue by vfxninjaeditor** [StudioPetrikas/Saulala#16] opened 2024-10-13 05:49 UTC
Despite the metadata of the RAW still displaying the correct capture date the text displayed in the frame is now the date in which the RAW file was modified. In this case the file is a processed RAW image saved from Topaz Photo AI for denoising.

**Comment by StudioPetrikas** [comment] 2024-10-13 11:57
I've been using 'modified date' for capture date, since it coincides what the camera date/time settings are, and does not get affected by file operations in the OS. The only thing that would change it, would be editing the file like you do in another software package. 

Now this is purely because I didn't want to get EXIF involved in the frame info, but I can see that it's unavoidable. 
I will likely make it look for 'create date' in the EXIF tags, then, if not found, fall back on the 'modified date'. 

Thanks for the report, it's very useful to know all the different use cases.

**Comment by vfxninjaeditor** [comment] 2024-10-13 16:35
Yeah, absolutely! I am having a blast with it so far. I don't think my photos have ever looked so good with so little time invested editing. Lightroom may have so many more features but I can't really bring myself to use it now lol.

I have been trying to export some of my RAWs from darktable as EXR and then doing some other film sim stuff in Blender like halation but unfortunately that process never quite gives me the same look as just throwing the original RAW into Saulala. So I am resorting to doing halation last but that has it's own issues since you lose access to any linear data.

**Comment by vfxninjaeditor** [comment] 2024-10-26 20:40
The new update fixes this issue with RAWs saved from Topaz Photo AI but now my original RAW files display the date as “None” on the border. I guess for some reason it can’t find the created date but is also not looking for the modified date either.

(unrelated, the tweaks to the sauces look great! Some, like Green Peach work/look a lot better on a wider variety of images from my tests now)

**Comment by StudioPetrikas** [comment] 2024-10-26 20:47
I'm such an idiot... Forgot to re-uncomment a line... Fixing...

Glad to hear about the sauces!

**Comment by StudioPetrikas** [comment] 2024-10-26 20:51
Hmm, no, hold on, everything's as intended. Could I get an example RAW file by any chance?

**Comment by vfxninjaeditor** [comment] 2024-10-26 21:02
Yeah, of course!
https://drive.proton.me/urls/BSKCETNK38#2LGuhGRBve8D

**Comment by StudioPetrikas** [comment] 2024-10-26 21:08
Hmm, okay, so it's not the file. 

Are you on a mac by chance?

![image](https://github.com/user-attachments/assets/4d278641-b2dc-4cfe-8492-8c934b39fd6c)

**Comment by vfxninjaeditor** [comment] 2024-10-26 21:11
I'm on Windows 10

**Comment by StudioPetrikas** [comment] 2024-10-26 21:24
Interesting. Since I can't replicate it, it's going to be a bit difficult to fix. 
What I really should do is that if the app fails to retrieve the date, just skip writing it into the frame instead of writing "None". 

Hasn't happened to any of the files I have, but I can see how that might happen. 

I'll keep in mind that previously the modified date was picked up correctly, only when I added the 'created date' query it fails to retrieve it. That's very likely relevant, although I have no idea how it works on my machine, but doesn't on yours. 

Sorry you're having so many issues with it.

**Comment by vfxninjaeditor** [comment] 2024-10-26 21:30
No, it's no issue! I can definitely work around it for the time being. The app is proving to save me a lot of time and with better results than I have ever had color wise for my photography. My previous way of editing in Lightroom was just too much work. More tools doesn't always equal better, and when you have ADHD it definitely doesn't help lol.

**Comment by StudioPetrikas** [comment] 2024-10-26 22:07
By ADHD people, for ADHD people. 

Anyway, I have to ask, but maybe running it as administrator could work? Maybe it's some permission issue. 
Also, please try moving Saulala to a different folder than it currently is in. Same with the RAW file. (Tried it on Android, seemed to work OK)

**Comment by vfxninjaeditor** [comment] 2024-10-27 17:50
Okay, so interesting results. Running as admin actually lets it read the date properly from the original RAW file. Keeping in mind that the .DNGs saved from Topaz work running the app as normal. But, running as admin for some reason causes a bug where I can no longer just drag images into the app. You have to open the image and navigate to it.

**Comment by lexusag** [comment] 2024-10-27 17:53
@vfxninjaeditor This behavior is normal when running as admin. It's because the app window now running as another user, and you can't drag and drop between users.

**Comment by vfxninjaeditor** [comment] 2024-10-27 18:05
> @vfxninjaeditor This behavior is normal when running as admin. It's because the app window now running as another user, and you can't drag and drop between users.

Thanks for educating me!

**Comment by StudioPetrikas** [comment] 2024-10-27 19:36
Thank you for helping troubleshoot the issue. 
Can you try v0.8.8.3 when you have a minute?

**Comment by vfxninjaeditor** [comment] 2024-10-28 23:36
I still have to open it in admin mode to get the date unfortunately

**Comment by StudioPetrikas** [comment] 2024-11-14 21:07
Possibly fixed in v0.8.9.2?

**Comment by vfxninjaeditor** [comment] 2024-11-21 03:38
Possibly a bug related to the same text? If I drag and drop a new image taken on a different date into the Saulala window it doesn't refresh the text with the correct date. It inherits the date of the previous image.

**Closed** 2024-12-11 16:04 UTC
