### ISSUE TITLE
App crashing after splash screen

### ISSUE THREAD

**Issue by shombando** [StudioPetrikas/Saulala#1] opened 2023-09-13 02:50 UTC
Hi @StudioPetrikas, I'm running into app crashes and I have tried to document the scenario and provided log snapshots. Please let me know if you need any more information or for me to try something else.

Android 13:
![android](https://github.com/StudioPetrikas/Saulala/assets/42972338/9fc35e6d-6e6b-47e0-bf0e-84b1d0872c6b)

I've granted Saulala permission:
![permissions](https://github.com/StudioPetrikas/Saulala/assets/42972338/9c57c8b8-a665-421f-aef5-3d64894755fc)

When I select a DNG from the camera it does not load the photo. The log shows that the app is trying to open `/storage` which is not possible to open in Android `/storage/emulated/0` is accessible to apps:
![logs1](https://github.com/StudioPetrikas/Saulala/assets/42972338/82125ddd-bd4e-4a0e-b082-ef3b08f7ba7b)

Saulala is able to create a settings file in `/storage/emulated/0/Documents/Saulala/` proving that file access permission is working:
![settings json](https://github.com/StudioPetrikas/Saulala/assets/42972338/ff50cffd-dc01-4050-9b43-bcf4e240d79f)

I uninstalled and reinstalled the app to recreate the issue. At first it was crashing on load and the log showed that it was trying to write to the settings file and failing, since it is not removed with the uninstall. I manually deleted the file and then was able to recreate the scenario above with the same error log. This is probably a separate issue, I'm happy to file it separately if it's helpful:
![logs](https://github.com/StudioPetrikas/Saulala/assets/42972338/18779f9a-5960-4020-80d5-2a5304df8643)

**Comment by StudioPetrikas** [comment] 2023-09-13 09:23
Thank you for such a detailed report!

Are you able to run it at all? Does it crash every time, or just on first launch?

What's interesting, that it's trying to access my "build" folder. I'd love to know wha file it's trying to access.

"File "/home/gus/agx_app... "

It's weird, because I use Linux just for building, so there can't be any hard-coded directories.

**Comment by shombando** [comment] 2023-09-13 21:48
> Are you able to run it at all? Does it crash every time, or just on first launch?

I'm able to launch it and get the file select screen every time.
![saulala](https://github.com/StudioPetrikas/Saulala/assets/42972338/2e484cbc-ed7a-45ca-a05c-a97cc512f58e)

> What's interesting, that it's trying to access my "build" folder. I'd love to know wha file it's trying to access.
> 
> "File "/home/gus/agx_app... "

Here's the expanded log, sorry I can't seem to export the text. But this log captures output from me pressing select file until the error. 
![fulllog](https://github.com/StudioPetrikas/Saulala/assets/42972338/af003e49-0516-4ebd-bfde-329367c679d8)

**Comment by StudioPetrikas** [comment] 2023-09-13 21:59
Thank you.
I'm sorry you're having this issue. I hope this doesn't discourage you from testing.

A quick google search returns a legacy storage permission problem, even though you're running Android 13.

I will either come up with a temp workaround or a fix, but it's rather difficult when I can't replicate the issue.

Meanwhile, can you try opening Saulala via a dng file? Using a file manager or a gallery? Some of them provide "Open As" option. I wonder if the issue is with the module that opens Android file selector.

Thank you once again!

**Comment by shombando** [comment] 2023-09-15 16:13
> Thank you. I'm sorry you're having this issue. I hope this doesn't discourage you from testing.

Not at all, this is what testing is all about. I'm happy to help, sometimes I'll just be a bit delayed.


> A quick google search returns a legacy storage permission problem, even though you're running Android 13.

That's strange!
 
> I will either come up with a temp workaround or a fix, but it's rather difficult when I can't replicate the issue.

Yeah, that's a bummer. Sorry my logs aren't comprehensive, I'll look into a better logger that you suggested.

> Meanwhile, can you try opening Saulala via a dng file? Using a file manager or a gallery? Some of them provide "Open As" option. I wonder if the issue is with the module that opens Android file selector.

This is from a clean install where I didn't launch Saulala at all. I went to native Files app and opened DNG file with Saulala. Here's the log:
![openwithsaulala](https://github.com/StudioPetrikas/Saulala/assets/42972338/ef7ec9b5-a42f-4208-81bb-59b122cc5fab)

> Thank you once again!

My pleasure!

**Comment by StudioPetrikas** [comment] 2023-09-26 20:37
Fixed in v0.1.5 Alpha, by force-updating "Plyer"

**Closed by StudioPetrikas** 2023-09-26 20:37 UTC
