### ISSUE TITLE
[Windows] Scrolling zooms the image

### ISSUE THREAD

**Issue by Thane5** [StudioPetrikas/Saulala#24] opened 2024-11-22 18:02 UTC
scrolling on the side panel zooms the image. the image can also cover the slider panel, which probably is not desired.

https://github.com/user-attachments/assets/76994964-ee2b-4e7d-a3f9-95cc16e62cf7

**Comment by StudioPetrikas** [comment] 2024-11-22 18:04
Thanks. I'll close this, because it's a duplicate of https://github.com/StudioPetrikas/Saulala/issues/21

Fixed in the upcoming beta, which should be out in 1-3 days.

**Closed by StudioPetrikas** 2024-11-22 18:04 UTC
